import type { ListingDetail } from "@/lib/types"

export const MOCK_LISTINGS: ListingDetail[] = [
  {
    id: "00000000-0000-0000-0000-000000000001",
    title: "Tita Nena's Boarding House",
    description:
      "A clean, safe, and homey boarding house in the heart of Lahug — just a 5-minute walk from USC Main. Tita Nena has been renting to female students for over 10 years and is known for being fair, approachable, and quick to fix any issues. Rooms are well-ventilated with natural light. Common bathroom is cleaned daily. There is a strict but reasonable curfew to ensure everyone's safety.",
    listing_type: "bedspace",
    gender_policy: "female_only",
    address: "123 M. Velez St., Lahug",
    barangay: "Lahug",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.3205,
    longitude: 123.8973,
    price_monthly: 4500,
    available_slots: 2,
    total_slots: 8,
    has_curfew: true,
    curfew_time: "10:00 PM",
    cooking_allowed: false,
    pets_allowed: false,
    lease_terms: ["monthly", "semestral"],
    house_rules:
      "No overnight male guests. Curfew at 10 PM on weekdays, 11 PM on weekends. No loud music after 9 PM. Clean common areas after use. Garbage must be sorted. Report any repairs immediately to Tita Nena.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: true,
    is_preferred: true,
    is_top_pick: false,
    preferred_note:
      "Our team visited on March 15. Rooms are clean and well-ventilated. Tita Nena is responsive and fair with house rules. Highly recommended for female students near USC.",
    average_rating: 4.9,
    review_count: 24,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "electricity" },
    ],
    landmarks: [
      { name: "USC Main Campus",   landmark_type: "school",   distance_meters: 400,  walking_minutes: 5,  latitude: 10.3157, longitude: 123.8854 },
      { name: "Gaisano Lahug",     landmark_type: "mall",     distance_meters: 650,  walking_minutes: 8,  latitude: 10.3249, longitude: 123.9001 },
      { name: "Lahug Health Center", landmark_type: "hospital", distance_meters: 900, walking_minutes: 11, latitude: 10.3190, longitude: 123.8915 },
    ],
    landlord: {
      id: "landlord-001",
      full_name: "Nena Santos",
      avatar_url: null,
      phone: "09171234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2024-01-15T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000002",
    title: "Casa Verde Bedspace",
    description:
      "Affordable and well-maintained bedspace in a quiet street in Talamban, perfect for CIT-U and UC students. The house has a dedicated study area, fast WiFi, and a friendly mix of students and young professionals. The caretaker Manang Rosie lives on-site and is available for any concerns.",
    listing_type: "bedspace",
    gender_policy: "mixed",
    address: "47 Talamban Rd., Talamban",
    barangay: "Talamban",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.3618,
    longitude: 123.9143,
    price_monthly: 3800,
    available_slots: 3,
    total_slots: 10,
    has_curfew: true,
    curfew_time: "11:00 PM",
    cooking_allowed: true,
    pets_allowed: false,
    lease_terms: ["monthly", "semestral", "annual"],
    house_rules:
      "Mixed boarding house — male and female floors are separate. Common kitchen is shared. Curfew at 11 PM. No smoking inside. Guests allowed until 9 PM only. Weekly room inspection every Saturday.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: false,
    is_preferred: false,
    is_top_pick: false,
    preferred_note: null,
    average_rating: 4.7,
    review_count: 18,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "cooking" },
    ],
    landmarks: [
      { name: "CIT-U Talamban Campus",          landmark_type: "school", distance_meters: 550,  walking_minutes: 7,  latitude: 10.3634, longitude: 123.9197 },
      { name: "University of Cebu - Talamban",  landmark_type: "school", distance_meters: 800,  walking_minutes: 10, latitude: 10.3551, longitude: 123.9090 },
      { name: "Robinsons Galleria",             landmark_type: "mall",   distance_meters: 1200, walking_minutes: 15, latitude: 10.3465, longitude: 123.9091 },
    ],
    landlord: {
      id: "landlord-002",
      full_name: "Rosario Dela Cruz",
      avatar_url: null,
      phone: "09281234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2024-03-20T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000003",
    title: "Kuya Ben's Studio Room",
    description:
      "A fully private studio room in Banilad — ideal for working adults and male students who want their own space. Comes with a private bathroom, individual electric meter, and a small ref. The building has CCTV and a security guard on duty at night. No curfew — perfect for those with shifting schedules.",
    listing_type: "studio",
    gender_policy: "male_only",
    address: "8 Banilad Road, Banilad",
    barangay: "Banilad",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.3494,
    longitude: 123.9055,
    price_monthly: 6500,
    available_slots: 1,
    total_slots: 4,
    has_curfew: false,
    curfew_time: null,
    cooking_allowed: true,
    pets_allowed: false,
    lease_terms: ["monthly", "annual"],
    house_rules:
      "No parties or loud noise after 10 PM. Keep hallways clean. Report maintenance issues within 24 hours. No subletting. Guests must register at the front desk.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: true,
    is_preferred: false,
    is_top_pick: false,
    preferred_note: null,
    average_rating: 4.8,
    review_count: 11,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "electricity" },
      { amenity: "aircon" },
      { amenity: "cooking" },
    ],
    landmarks: [
      { name: "UV Visayas Main",      landmark_type: "school",   distance_meters: 600,  walking_minutes: 8,  latitude: 10.3414, longitude: 123.9037 },
      { name: "Banilad Town Centre",  landmark_type: "mall",     distance_meters: 300,  walking_minutes: 4,  latitude: 10.3521, longitude: 123.9073 },
      { name: "Cebu Doctors Hospital", landmark_type: "hospital", distance_meters: 1500, walking_minutes: 18, latitude: 10.3289, longitude: 123.8989 },
    ],
    landlord: {
      id: "landlord-003",
      full_name: "Benjamin Torres",
      avatar_url: null,
      phone: "09351234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2023-11-10T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000004",
    title: "Mabolo Girls Boarding House",
    description:
      "A safe and affordable boarding house for female students and young professionals in Mabolo. Minutes away from Cebu Normal University and multiple jeepney routes. The friendly landlord Ate Marites lives on-site and personally reviews all applicants. Common area has a TV lounge and a small garden.",
    listing_type: "bedspace",
    gender_policy: "female_only",
    address: "56 F. Ramos St., Mabolo",
    barangay: "Mabolo",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.3140,
    longitude: 123.9098,
    price_monthly: 3200,
    available_slots: 4,
    total_slots: 12,
    has_curfew: true,
    curfew_time: "9:30 PM",
    cooking_allowed: false,
    pets_allowed: false,
    lease_terms: ["monthly", "semestral"],
    house_rules:
      "Female tenants only. Curfew strictly at 9:30 PM. No male guests beyond the living room. Rooms are inspected every 2 weeks. Rent due on the 5th of every month.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: true,
    is_preferred: true,
    is_top_pick: false,
    preferred_note:
      "Visited by our team in February. Rooms are tidy and well-maintained. Ate Marites personally screens all tenants — this is one of the most trusted boarding houses near CNU.",
    average_rating: 4.6,
    review_count: 32,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
    ],
    landmarks: [
      { name: "Cebu Normal University", landmark_type: "school",   distance_meters: 350, walking_minutes: 4, latitude: 10.3002, longitude: 123.8981 },
      { name: "SM City Cebu",           landmark_type: "mall",     distance_meters: 700, walking_minutes: 9, latitude: 10.3165, longitude: 123.9094 },
      { name: "Mabolo Church",          landmark_type: "church",   distance_meters: 200, walking_minutes: 3, latitude: 10.3120, longitude: 123.9076 },
    ],
    landlord: {
      id: "landlord-004",
      full_name: "Marites Villanueva",
      avatar_url: null,
      phone: "09461234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2023-08-05T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000005",
    title: "Urgello Private Room",
    description:
      "A clean and affordable private room near Urgello, close to Cebu Doctors University and several hospitals — perfect for nursing and medical students. The room has its own lock, a ceiling fan, and a study desk. Building has 24/7 water supply and backup generator.",
    listing_type: "private_room",
    gender_policy: "mixed",
    address: "22 Urgello St., Parian",
    barangay: "Parian",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.2985,
    longitude: 123.8998,
    price_monthly: 5500,
    available_slots: 1,
    total_slots: 6,
    has_curfew: false,
    curfew_time: null,
    cooking_allowed: false,
    pets_allowed: false,
    lease_terms: ["monthly"],
    house_rules:
      "No cooking inside the room. Common kitchen is available 6 AM–9 PM. Visitors allowed until 8 PM. Keep noise levels low — many tenants have shifting schedules.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: false,
    is_preferred: false,
    is_top_pick: false,
    preferred_note: null,
    average_rating: 4.5,
    review_count: 8,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "electricity" },
    ],
    landmarks: [
      { name: "Cebu Doctors University", landmark_type: "school",   distance_meters: 500, walking_minutes: 6, latitude: 10.2958, longitude: 123.8934 },
      { name: "Cebu Doctors Hospital",   landmark_type: "hospital", distance_meters: 300, walking_minutes: 4, latitude: 10.2964, longitude: 123.8971 },
      { name: "Carbon Market",           landmark_type: "mall",     distance_meters: 800, walking_minutes: 10, latitude: 10.2940, longitude: 123.9006 },
    ],
    landlord: {
      id: "landlord-005",
      full_name: "Pedro Mercado",
      avatar_url: null,
      phone: "09571234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2024-02-18T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000006",
    title: "IT Park Residences",
    description:
      "Premium private room in Apas, right beside the Cebu IT Park — perfect for BPO workers and IT professionals. The room includes aircon, private bathroom, fast fiber internet, and a small ref. Building has 24/7 security, CCTV, and a rooftop area. No curfew, great for night shift workers.",
    listing_type: "private_room",
    gender_policy: "mixed",
    address: "3 Salinas Drive, Apas",
    barangay: "Apas",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.3298,
    longitude: 123.9108,
    price_monthly: 7500,
    available_slots: 1,
    total_slots: 8,
    has_curfew: false,
    curfew_time: null,
    cooking_allowed: true,
    pets_allowed: true,
    lease_terms: ["monthly", "annual"],
    house_rules:
      "Professional tenants preferred. No subletting. Guests must be registered at the front desk. Small pets allowed with ₱500 pet deposit. Cooking allowed in designated kitchen area only.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: true,
    is_preferred: true,
    is_top_pick: true,
    preferred_note:
      "StayPH team visited in April. This is the best-maintained property we've seen near IT Park. Highly recommended for working professionals. Security and cleanliness are top-notch.",
    average_rating: 4.9,
    review_count: 41,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "electricity" },
      { amenity: "aircon" },
      { amenity: "cooking" },
      { amenity: "laundry" },
    ],
    landmarks: [
      { name: "Cebu IT Park",      landmark_type: "mall",   distance_meters: 150,  walking_minutes: 2,  latitude: 10.3310, longitude: 123.9073 },
      { name: "USC North Campus",  landmark_type: "school", distance_meters: 900,  walking_minutes: 11, latitude: 10.3217, longitude: 123.9003 },
      { name: "Ayala Center Cebu", landmark_type: "mall",   distance_meters: 1100, walking_minutes: 14, latitude: 10.3182, longitude: 123.9056 },
    ],
    landlord: {
      id: "landlord-006",
      full_name: "Jerome Alcantara",
      avatar_url: null,
      phone: "09681234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2023-06-01T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000007",
    title: "Colon Budget Bedspace",
    description:
      "The most affordable bedspace listing in downtown Cebu — great for students who need to be close to the city center. Basic but clean. The house has been running for 20 years and has a loyal base of returning tenants. Ideal for those on a tight budget who prioritize location over amenities.",
    listing_type: "bedspace",
    gender_policy: "mixed",
    address: "11 Colon St., Parian",
    barangay: "Parian",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.2958,
    longitude: 123.9012,
    price_monthly: 2800,
    available_slots: 5,
    total_slots: 20,
    has_curfew: true,
    curfew_time: "10:30 PM",
    cooking_allowed: false,
    pets_allowed: false,
    lease_terms: ["monthly"],
    house_rules:
      "Curfew at 10:30 PM. No cooking inside rooms. Shared bathrooms cleaned by staff every morning. Visitors allowed in common area only until 8 PM.",
    status: "active",
    is_id_verified: false,
    is_photo_verified: true,
    is_admin_verified: false,
    is_site_visited: false,
    is_preferred: false,
    is_top_pick: false,
    preferred_note: null,
    average_rating: 4.1,
    review_count: 47,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "water" },
      { amenity: "electricity" },
    ],
    landmarks: [
      { name: "Colon Street",                    landmark_type: "mall",   distance_meters: 50,  walking_minutes: 1, latitude: 10.2950, longitude: 123.9017 },
      { name: "Carbon Market",                   landmark_type: "mall",   distance_meters: 400, walking_minutes: 5, latitude: 10.2940, longitude: 123.9006 },
      { name: "University of the Visayas Main",  landmark_type: "school", distance_meters: 600, walking_minutes: 7, latitude: 10.2934, longitude: 123.9015 },
    ],
    landlord: {
      id: "landlord-007",
      full_name: "Danilo Espiritu",
      avatar_url: null,
      phone: "09791234567",
      is_phone_verified: true,
      is_id_verified: false,
      created_at: "2024-04-10T00:00:00Z",
    },
  },
  {
    id: "00000000-0000-0000-0000-000000000008",
    title: "Pardo Family Boarding House",
    description:
      "A family-run boarding house for female tenants in the quiet neighborhood of Pardo. The landlord, Nanay Celing, has been hosting students and teachers for 15 years. The house has a large shared sala, a garden with plants and a hammock, and home-cooked meals available for an extra ₱800/month.",
    listing_type: "bedspace",
    gender_policy: "female_only",
    address: "88 Pardo Blvd., Pardo",
    barangay: "Pardo",
    city: "Cebu City",
    province: "Cebu",
    latitude: 10.2701,
    longitude: 123.8798,
    price_monthly: 3500,
    available_slots: 2,
    total_slots: 9,
    has_curfew: true,
    curfew_time: "10:00 PM",
    cooking_allowed: false,
    pets_allowed: false,
    lease_terms: ["monthly", "semestral"],
    house_rules:
      "Female tenants only. Curfew at 10 PM. Optional meals available. No smoking anywhere on the property. Keep common areas tidy. Laundry area open 7 AM to 7 PM.",
    status: "active",
    is_id_verified: true,
    is_photo_verified: true,
    is_admin_verified: true,
    is_site_visited: false,
    is_preferred: false,
    is_top_pick: false,
    preferred_note: null,
    average_rating: 4.7,
    review_count: 19,
    listing_photos: [
      { url: "", is_cover: true },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
      { url: "", is_cover: false },
    ],
    listing_amenities: [
      { amenity: "wifi" },
      { amenity: "water" },
      { amenity: "laundry" },
    ],
    landmarks: [
      { name: "Pardo Church",            landmark_type: "church", distance_meters: 200,  walking_minutes: 3,  latitude: 10.2689, longitude: 123.8778 },
      { name: "SWU PHINMA Pardo Campus", landmark_type: "school", distance_meters: 700,  walking_minutes: 9,  latitude: 10.2756, longitude: 123.8744 },
      { name: "SM Seaside",              landmark_type: "mall",   distance_meters: 2000, walking_minutes: 25, latitude: 10.2537, longitude: 123.8704 },
    ],
    landlord: {
      id: "landlord-008",
      full_name: "Celia Montecillo",
      avatar_url: null,
      phone: "09891234567",
      is_phone_verified: true,
      is_id_verified: true,
      created_at: "2023-09-22T00:00:00Z",
    },
  },
]
